  
name: Rebuild

on:
  schedule:
  - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Call a webhook
      run: |
        curl -X POST -d {} https://webhook.gatsbyjs.com/hooks/data_source/publish/96a6b5bb-3a52-4cee-a8e6-eec6aa6c2f56
